name: hesaplamaaraci
description: Hesaplamalar için bir araç
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/guc.png
    - assets/images/surtunmekaybi.png
    - assets/images/debi.png
    - assets/images/basmayuksekligi.png
    - assets/images/hidrolikverim.png
    - assets/images/motor.png
    - assets/images/frictionloss/borucapi.png
    - assets/images/frictionloss/boruuzunlugu.png
    - assets/images/frictionloss/sicaklikolcer.png

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.12
  sqflite: ^2.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
